---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE}
rm(list=ls()) 
library(MASS)
library(data.table)
library(gtools)
library(mvtnorm)
getwd()
```

## S&P

```{r,echo=FALSE}
lf <- list.files(path = "/home/hattori/デスクトップ/Merton model and Poisson process with Log Normal intensity function/R/data",full.names = TRUE) 
for (i in 1:1) {
  data<-fread(lf[i],header = T)
  names(data)[which(names(data)=="Up/Down")]<-"date"
  data$date<-as.Date(data$date, format = "%m/%d/%Y")
}
data
plot(data$date,data$Defaulted,type = "l")
```

```{r}
mean(data[data$date>as.Date("1981-01-01") &data$date<as.Date("2019-01-01")]$Defaulted/data[data$date>as.Date("1981-01-01") &data$date<as.Date("2019-01-01")]$Totals)
data1980<-data[data$date>as.Date("1980-01-01")]
data1990<-data[data$date>as.Date("1990-01-01")]
data1980;data1990
```

$$
\begin{eqnarray}
\mathrm{P}[X_t=k_t]
&=&\int^{\infty}_{-\infty}\frac{N!}{k_t!(N-k_t)!}G(y)^{k_t}(1-G(y))^{N-k_t}\phi(y)\ \mathrm{d}y\\
&=&\int^{\infty}_{-\infty}\frac{N!}{k_t!(N-k_t)!}\Phi\left(\frac{\Phi^{-1}(p')-\sqrt{\rho_A}y}{\sqrt{1-\rho_A}} \right)^{k_t}(1-\Phi\left(\frac{\Phi^{-1}(p')-\sqrt{\rho_A}y}{\sqrt{1-\rho_A}} \right))^{N-k_t}\phi(y)\ \mathrm{d}y
\end{eqnarray}
$$

```{r}
P_k<-function(n,k,rho,p_){
p <- function(y) {
  Y<-log(p_/(1-p_))
  Phi<-pnorm((Y-sqrt(rho)*y)/(sqrt(1-rho)))
  choose(n,k)*
    (Phi**k)*(1-Phi)**(n-k)*dnorm(y,mean = 0,sd=1)
}
  integrate(p,-Inf,Inf)[[1]]  
}

```


```{r eval=FALSE}
k<-data1980$Defaulted
N<-data1980$Totals

f<-function(x){

  rho<-1/(1+exp(-x[1]))
  p_ <-1/(1+exp(-x[2]))

ll<-0
for(t in 1:length(k)){
 ll<-ll+log(P_k(N[t],k[t],rho,p_))
}

return(ll)
}

res<-optim(c(0,0),hessian=TRUE,f,control=list(fnscale=-1))
1/(1+exp(-res$par[1]))
1/(1+exp(-res$par[2]))

```






