---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### -----

$$
X_{t+1}\sim\mathrm{NBD}(\mathrm{size}=K_t,\mathrm{prob}=\frac{K_0}{M_0+K_0}),\quad t\ge0
$$

$$
M_t=M_0+M_0/L_0\sum_{s=1}^t X_s\hat{d}_{t-s},\quad t\ge 1
$$

$$
K_t=K_0+K_0/L_0\sum_{s=1}^t X_s\hat{d}_{t-s},\quad t\ge 1
$$

$$
{\hat{d}}^t=r^t
$$

$$
\begin{eqnarray}
K_n=K_0+(K_{n-1}-K_0)r+K_0/L_0X_n
\end{eqnarray}
$$

```{r}
K0<-10;M0<-5;K<-c();x<-c();r<-0.3;L0<-5/0.7
for (i in 1:10){

t<-1
K[t]<-K0             
x[t]<-rnbinom(1,size=K[t],p=K0/(M0+K0))

for(t in 2:5000) {
K[t]<-(K[t-1]-K0)*r+K0/L0*x[t-1]+K0
x[t]<-rnbinom(1,size=K[t],p=K0/(M0+K0))

}

ts.plot(K,main=L0)
L0<-L0+0.1

}
ts.plot(x)
```

```{r}
    K0<-runif(1,1,5)
    M0<-runif(1,1,5)
    r <-runif(1,0.1,0.9)
    L0<-runif(1,M0,M0/(1-r)/0.9)

    K0;M0;r;L0;M0/(1-r)/L0
```



```{r}
K<-K0
M<-M0
x<-c()

t<-1
x[t]<-rnbinom(1,size=K,p=K0/(M0+K0))
              
for(t in 2:1000) {
K<-(K-K0)*r+K0/L0*x[t-1]+K0
M<-(M-M0)*r+M0/L0*x[t-1]+M0
x[t]<-rnbinom(1,size=K,p=K0/(M0+K0))
}

ts.plot(x)
```







```{r,echo=FALSE}
#-------------------NBD-------------------
seAIC_1<-function(x){
  
I<-length(x)

seNBD<- function(x){
  return(function(ps){
    
    N<-length(x)
    ll<-0.0
    K0<-exp(ps[1])
    M0<-exp(ps[2])
    L0<-exp(ps[3])
    r<-1/(1+exp(-ps[4]))
    
    t<-1
    K<-K0
    ll<-ll+dnbinom(x[t],size=K,p=K0/(M0+K0),log=TRUE)
    for(t in 2:N){
    K<-(K-K0)*r+K0/L0*x[t-1]+K0
    ll<-ll+dnbinom(x[t],size=K,p=K0/(M0+K0),log=TRUE)
    }
    return(ll)
  }
  )
}

seNBD_exp<-optim(c(0.00001,0.00001,0.000001,0.1),seNBD(x),method="L-BFGS-B",hessian=TRUE,control=list(fnscale=-1))
K0<-exp(seNBD_exp$par[1])
M0<-exp(seNBD_exp$par[2])
L0<-exp(seNBD_exp$par[3])
r<-1/(1+exp(-seNBD_exp$par[4]))
n<-M0/(L0*(1-r))
mu<-M0/(1-n)
p=K0/(M0+K0)

AIC<-(-seNBD_exp$value+4)*2
BIC<--2*seNBD_exp$value+4*log(I)

df<-data.frame(AIC=AIC,K0=K0,M0=M0,"M0/K0"=M0/K0,L0,r=r,mu,n=n)
return(df)
}
```

```{r,echo=FALSE}
AIC_fun<-function(x){
  
I<-length(x)

#-------------------NBD-------------------

ll_NBD_d0_r<- function(x){
  return(function(ps){
    N<-length(x)
    ll<-0.0
    lam<-exp(ps[1])
    p<-1/(1+exp(-ps[2]))
    n<-1/(1+exp(-ps[3]))
    r<-1/(1+exp(-ps[4]))
    d0<-n*(1-r)/(1/p-1)
    
    t<-1
    alpha_t<-lam
    ll<-ll+dnbinom(x[t],size=alpha_t,p=p,log=TRUE)
    for(t in 2:(N)){
    alpha_t<-(alpha_t-lam)*r+d0*x[t-1]+lam
    ll<-ll+dnbinom(x[t],size=alpha_t,p=p,log=TRUE)
    }
    return(ll)
  }
  )
}

NBD_exp<-optim(c(0.0,0.0,0.0,0.0),ll_NBD_d0_r(x),method="L-BFGS-B",hessian=TRUE,control=list(fnscale=-1))
  lam<-exp(NBD_exp$par[1])
  p<-1/(1+exp(-NBD_exp$par[2]))
  n<-1/(1+exp(-NBD_exp$par[3]))
  r<-1/(1+exp(-NBD_exp$par[4]))
  d0<-n*(1-r)/(1/p-1)
  mu<-lam*(1/p-1)/(1-n)
AIC<-(-NBD_exp$value+4)*2
BIC<--2*NBD_exp$value+4*log(I)

df<-data.frame(AIC=AIC,K0=lam,M0=lam*(1/p-1),"M0/K0"=(1/p-1),L0=lam*(1/p-1)/(n*(1-r)),beta=r,mu,p,n)

#---------------------------------------

return( list(df) )
}
```

```{r}
    K0;M0;r;L0;M0/L0/(1-r)
AIC_fun(x)
seAIC_1(x)
```

















```{r}

L0<-matrix(nrow=2, ncol=2);M0<-c();r<-c()

    K0[1:2]  <-c(8,5)
    M0[1:2]  <-c(5,4)
    r [1:2]  <-c(0.3,0.6)
    L0[1,1:2]<-c(30,15)
    L0[2,1:2]<-c(27,20)


#for (j in 1:5) {

x<-matrix(nrow = 1000,ncol = 2)
K<-matrix(nrow = 1000,ncol = 2)
M<-matrix(nrow = 1000,ncol = 2)
#  S<-/(1-r)
  
for (i in 1:2){
t<-1
K[t,i]<-K0[i]   
M[t,i]<-M0[i]     
x[t,i]<-rnbinom(1,size=K[t,i],p=K0[i]/(M0[i]+K0[i]))
}


for(t in 2:dim(x)[1]) {
  for (i in 1:2){
K[t,i]<-(K[t-1,i]-K0[i])*r[i]+(K0[i]/L0[i,])%*%x[t-1,]+K0[i]
M[t,i]<-(M[t-1,i]-M0[i])*r[i]+(M0[i]/L0[i,])%*%x[t-1,]+M0[i]
x[t,i]<-rnbinom(1,size=K[t,i],p=K0[i]/(M0[i]+K0[i]))
  }
}

for (i in 1:2) {

#ts.plot(x[,i],main=L0[1,1])
  ts.plot(K[,i],main=sum(M0/(1-r)/L0))
#  ts.plot(M[,i])
}
L0[1,1]<-L0[1,1]-1
#}
    
```

```{r,echo=FALSE}
#-------------------seNBD-------------------
seAIC_n<-function(x){

  I<-dim(x)[1]
  dim<-dim(x)[2]

    seNBD<- function(x,i){
      return(function(ps){
    
      N<-dim(x)[1]
      dim<-dim(x)[2]
      ll<-0.0
      L<-c()
      r<-1/(1+exp(-ps[1]))
      K0<-exp(ps[2])
      M0<-exp(ps[3])
      L[1:dim]<-exp(ps[4:(4+dim-1)])
#      for (j in 1:dim) {
#      L[j]<-exp(ps[(3+j)])
#      if(j!=i) { L[j]<-exp(ps[(3+j)]+ps[(3+i)]) }
#      }
      
      t<-1
      K<-K0
      ll<-ll+dnbinom(x[t,i],size=K,p=K0/(M0+K0),log=TRUE)
      for(t in 2:N){
      K<-K0+(K-K0)*r+(K0/L)%*%x[(t-1),]
      ll<-ll+dnbinom(x[t,i],size=K,p=K0/(M0+K0),log=TRUE)
      }
      return(ll)
    }
    )
    }
    ini<-c(seq(0.1,0.1,length=dim+3))
    df<-data.frame()
    x<-matrix(as.matrix(x),nrow(x),ncol(x))

for (i in 1:dim) {
seNBD_exp<-optim(ini,seNBD(x,i),method="L-BFGS-B",hessian=TRUE,control=list(fnscale=-1))
r<-1/(1+exp(-seNBD_exp$par[1]))
K0<-exp(seNBD_exp$par[2])
M0<-exp(seNBD_exp$par[3])
    L<-c()
L[1:dim]<-exp(seNBD_exp$par[4:(4+dim-1)])
#for (j in 1:dim) {
#  L[j]<-exp(seNBD_exp$par[3+j])
#  if(j!=i) { L[j]<-exp(seNBD_exp$par[3+j]+seNBD_exp$par[3+i]) }
#}
AIC<-(-seNBD_exp$value+length(ini))*2
BIC<--2*seNBD_exp$value+length(ini)*log(I*dim)

df1<-data.frame(dim,AIC=AIC,K0=K0,M0=M0,"M0/K0"=M0/K0,L[1],L[2],L[3],L[4],L[5],L[6],L[7],L[8],L[9],L[10],L[11],L[12],L[13],r)
df<-rbind(df,df1)
}
    
return(df)
}
```

```{r}
K0;M0;r;L0

a<-seAIC_n(x)
a
```








```{r}
L0<-matrix(nrow=2, ncol=2);K0<-c();M0<-c();r<-c()
    K0[1:2]<-c(10,5)#runif(2,0.1,1)
    M0[1:2]<-c(3,1)#runif(2,0.1,1)
    r[1:2] <-c(0.1,0.2)#runif(2,0.1,0.9)
    L0[1,1:2]<-c(3.5,15)#runif(2,M0[1]/(1-r),M0[1]/(1-r[1])*10)
    L0[2,1:2]<-c(8,5)#runif(2,M0[2]/(1-r),M0[2]/(1-r[2])*10)
#    L0[3,1:3]<-runif(3,0,30)



    K0;M0;r;L0;1/(1-r)/L0;M0/(1-r)/L0

```

```{r,warning = FALSE}


x<-matrix(nrow = 10000,ncol = 2)
for (i in 1:2) {
t<-1
  K<-K0[i]
x[t,i]<-rnbinom(1,size=K,p=K0[i]/(M0[i]+K0[i]))
    y<-c(x[t,])
}

  for(t in 2:dim(x)[1]){
        for (i in 1:2) {

  K<-K0[i]+(K-K0[i])*r[i]+(K0[i]/L0[i,])%*%y
  x[t,i]<-rnbinom(1,size=K,p=K0[i]/(M0[i]+K0[i]))
    }
      y<-c(x[t,])

  }
ts.plot(x[,1]);ts.plot(x[,2])
```


```{r,echo=FALSE,eval=FALSE}
#-------------------seNBD-------------------
seAIC_n<-function(x){

  res<-list()
  I<-dim(x)[1]
  dim<-dim(x)[2]

    seNBD<- function(x){
      return(function(ps){
    
      N<-dim(x)[1]
      dim<-dim(x)[2]
      r<-c();K0<-c();M0<-c();L<-c()
      ll<-numeric(dim)

      r [1:dim]<-1/(1+exp(-ps[1:(dim)]))
      K0[1:dim]<-exp(ps[(dim+1):(dim+dim)])
      M0[1:dim]<-exp(ps[(dim+dim+1):(dim+dim+dim)])
      L [1:(dim*dim)]<-exp(ps[(dim+dim+dim+1):(dim+dim+dim+dim*dim)])
      for (j in 1:dim) {

      t<-1
      K<-K0[j]
      ll[j]<-ll[j]+dnbinom(x[t,j],size=K,p=K0[j]/(M0[j]+K0[j]),log=TRUE)
      for(t in 2:N){
      K<-K0[j]+(K-K0[j])*r[j]+(K0[j]/L[((j-1)*dim+1):((j-1)*dim+dim)])%*%(x[(t-1),])
      ll[j]<-ll[j]+dnbinom(x[t,j],size=K,p=K0[j]/(M0[j]+K0[j]),log=TRUE)
      
      }
      
      }
      
      return(sum(ll))
    }
    )
    }

    ini<-c(rep(1,(dim)),rep(0,(2*dim)),rep(0,(dim*dim)))
    df<-data.frame()
    x<-matrix(as.matrix(x),nrow(x),ncol(x))

#          for (i in 1:dim) {
seNBD_exp<-optim(ini,seNBD(x),method="L-BFGS-B",hessian=TRUE,control=list(fnscale=-1))
                 #,lower=c(rep(-Inf,(dim*3)),-Inf,log(1),log(1),-Inf ),upper = c(rep(Inf,(dim*3)),rep(Inf,(dim*dim)) ) )
r<-c();K0<-c();M0<-c();L<-c()
r[1:dim]<-1/(1+exp(-seNBD_exp$par[1:(dim)]))
K0[1:dim]<-exp(seNBD_exp$par[(dim+1):(dim+dim)])
M0[1:dim]<-exp(seNBD_exp$par[(dim+dim+1):(dim+dim+dim)])
L[1:(dim*dim)]<-exp(seNBD_exp$par[(dim+dim+dim+1):(dim+dim+dim+dim*dim)])

AIC<-(-seNBD_exp$value+length(ini))*2
BIC<--2*seNBD_exp$value+length(ini)*log(I*dim)

df1<-data.frame(AIC=AIC,K0=K0[1],K0[2],M0=M0[1],M0[2],L[1],L[2],L[3],L[4],r[1],r[2])#,L[4],L[5],L[6],L[7],L[8],L[9],L[10],L[11],L[12],L[13],"M0/K0"=M0/K0,r)[1,]
df<-rbind(df,df1)
#}
return(df)
}

```

```{r}
K0;M0;r;L0;sum(M0/(1-r)/L0)

a<-seAIC_n(x)
a;seAIC_1(x[,1]);seAIC_1(x[,2])
```












