---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### NBD($\omega>0$)

$$
X_t\sim \mbox{NBD}(\alpha_{t-1}=\frac{{\nu}_{t-1}}{\omega},p=\frac{1}{\omega x +1})
$$

$$
\alpha_{t}=\lambda_0+\sum_{s=1}^{t}X_s d_{t-s}\qquad(t\ge 1),\alpha_0=\lambda_0
$$

$$
d_{t}=d_{0}r^t,\quad n=\sum_{t=0}^{\infty}d_{t}=\frac{d_{0}}{1-r},\quad0\le r<1
$$

$$
p=\frac{1}{\omega+1}\to\omega=\frac{M_0}{K_0}=\frac{1}{p}-1
$$

$$
\alpha_0=\frac{\nu_0}{\omega}=K_0\qquad(\because\nu_0=M_0)
$$


```{r}
ll_NBD_d0_r<- function(x){
  return(function(ps){
    N<-length(x)
    ll<-0.0
    lam<-exp(ps[1])
    p<-1/(1+exp(-ps[2]))
    n<-1/(1+exp(-ps[3]))
    r<-1/(1+exp(-ps[4]))
    d0<-n*(1-r)
    
    t<-1
    alpha_t<-lam
    ll<-ll+dnbinom(x[t],size=alpha_t,p=p,log=TRUE)
    for(t in 2:(N-1)){
    alpha_t<-(alpha_t-lam)*r+d0*x[t-1]+lam
    ll<-ll+dnbinom(x[t],size=alpha_t,p=p,log=TRUE)
    }
    return(ll)
  }
  )
}

#NBD_exp<-optim(c(0.0,0.0,0.0,0.0),ll_NBD_d0_r(x),hessian=TRUE,control=list(fnscale=-1))
#  lam<-exp(NBD_exp$par[1])
#  p<-1/(1+exp(-NBD_exp$par[2]))
#  n<-1/(1+exp(-NBD_exp$par[3]))
#  r<-1/(1+exp(-NBD_exp$par[4]))
#  mu<-lam*(1/p-1)/(1-n)
#AIC<-(-NBD_exp$value+4)*2
#BIC<--2*NBD_exp$value+4*log(I)

#AIC
#BIC
#lam    #K0
#1/p-1  #M0/K0
#mu     #定常値p
#n      #分岐比
```

### NBD($\omega>0$)

- $d_0\neq 0,d_{t}=0,t\ge 1$


$$
\alpha_{t}=
\left\{
\begin{array}{cc}  
\lambda_0+d_0 X_t & t\ge 1 \\
\lambda_0 & t=0  
\end{array}
\right.
$$

$$
X_t\sim \mbox{NBD}(\alpha_{t-1}=\frac{{\nu}_{t-1}}{\omega},p=\frac{1}{\omega x +1})
$$

$$
\alpha_{t}=\lambda_0+X_t d_{0}\qquad(t\ge 1),\alpha_0=\lambda_0
$$

$$
d_{t}=0\quad(t\neq 0),\quad n=d_{0}
$$

$$
p=\frac{1}{\omega+1}\to\omega=\frac{M_0}{K_0}=\frac{1}{p}-1
$$

$$
\alpha_0=\frac{\nu_0}{\omega}=K_0\qquad(\because\nu_0=M_0)
$$

```{r}

ll_NBD_d0<- function(data){
  return(function(ps){
    N<-length(data)
    ll<-0.0
    lam<-exp(ps[1])
    p<-1/(1+exp(-ps[2]))
    d0<-exp(ps[3])
    t<-1
    alpha_t<-lam
    ll<-ll+dnbinom(data[t],size=alpha_t,p=p,log=TRUE)
    for(t in 2:N){
    alpha_t<-lam+d0*data[t-1]
    ll<-ll+dnbinom(data[t],size=alpha_t,p=p,log=TRUE)
    }
    return(ll)
  }
  )
}

#NBD_exp<-optim(c(0,0,0),ll_NBD_d0(x),hessian=TRUE,control=list(fnscale=-1))
#    lam<-exp(NBD_exp$par[1])
#    p<-1/(1+exp(-NBD_exp$par[2]))
#    d0<-exp(NBD_exp$par[3])
#    n<-d0

#mu=lam*(1/p-1)/(1-n)

#AIC
#BIC
#lam    #K0
#1/p-1  #M0/K0
#mu     #定常値
#n      #分岐比
```


