---
title: "2dim"
output: html_document
date: "2022-08-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE}
rm(list=ls()) 
library(MASS)
library(data.table)
library(gtools)
library(mvtnorm)
getwd()
```

```{r}
#逆行列
matpow <- function(x, pow) {
   y <- eigen(x)
   y$vectors %*% diag( (y$values)^pow ) %*% solve(y$vectors)
 }
```

#### 正規コピュラに従う乱数$\vec{u}$の生成方法

- (1):$\vec{x}=(x_1,\cdots,x_n)$を$n$変量正規乱数として生成

$$
\vec{x}\sim \mbox{N}_{n}(\vec{0},\Sigma)
$$

- (2):$\vec{u}=\Phi(\vec{x})$

- (3):$i$番目の周辺分布が$F_i$のとき:$F_i^{-1}(u_i)$.

$$
\vec{X}\sim \mbox{N}_n(\vec{0},\Sigma)\to \vec{U}=\Phi(\vec{X}) \to \vec{F}=\vec{F}^{-1}(\vec{U})
$$

```{r}
dim<-1e1
sigma<-matrix(0,nrow = dim,ncol = dim)
theta<-0.2
d<-theta**(0:(dim-1))

a<-c()
for (i in (dim):1) {
a<-c(a,d[1:i])
}

sigma[lower.tri(sigma,diag = T)]<-a
sigma<-sigma+t(sigma)
diag(sigma)<-diag(sigma)/2

#sigma
```

```{r}
X<-rmvnorm(1,mean=rep(0,dim),sigma=sigma) #多変量正規分布
U<-pnorm(X)#正規コピュラに従う乱数
X;U
```


#### 推定

```{r}
cop_AIC<-function(data,ini){

cop<-function(data){
  return(function(ps){
    
    N<-length(data)
    
    ll<-0
    theta<-1/(1+exp(-ps[1]))
    omega<-qnorm(data)
    sigma<-matrix(0,nrow = N,ncol = N)
    d<-theta**(0:(N-1))

    a<-c()
    for (i in N:1) {
      a<-c(a,d[1:i])
      }

    sigma[lower.tri(sigma,diag = T)]<-a
    sigma<-sigma+t(sigma)
    diag(sigma)<-diag(sigma)/2
    
        ll<- -N/2*log(det(sigma))-1/2*t(omega)%*%(matpow(sigma,-1)-diag(N))%*%omega
    
    return(ll)
  }
)
}

  par<-optim(ini,cop(data),method="L-BFGS-B",control = list(fnscale = -1),hessian = TRUE)
  theta<-1/(1+exp(-par$par[1]))

return(par)

}
```


```{r}
a<-cop_AIC(c(U),0)
1/(1+exp(-a$par))
```









---

```{r}
rm(list=ls()) 
```


$$
\Sigma\equiv\begin{pmatrix}
1 & d_1 & d_2 & \cdots &d_{T-1} \\[6pt]
d_1 & 1 & d_1 & \ddots &\vdots \\[6pt]\ddots&\ddots&\ddots&\ddots&\ddots\\[6pt]\vdots&\ddots&\ddots&\ddots&d_1\\[6pt]d_{T-1}&\cdots&d_2&d_1&1
\end{pmatrix}\tag{1}
$$

## exp

$$
d_i=\theta^i,\ 0\le\theta\le1
$$



###対角行列の作成

```{r}
dim<-5e2
sigma<-matrix(0,nrow = dim,ncol = dim)
theta<-0.9
d<-theta**(0:(dim-1))

a<-c()
for (i in (dim):1) {
a<-c(a,d[1:i])
}

sigma[lower.tri(sigma,diag = T)]<-a
sigma<-sigma+t(sigma)
diag(sigma)<-diag(sigma)/2

#sigma
```


$$
\{y_t,1\le t\le T\}
$$

$$
(y_1,\cdots,y_T)^T\sim\mathrm{N}_T(0,\Sigma)
$$

```{r}
y<-rmvnorm(1,mean=rep(0,dim),sigma=sigma)
data.frame(t(y))
```




$$
\hat U_{it}=\sqrt{\rho_A}y_t+\sqrt{1-\rho_A}\epsilon_{it}\tag{2}
$$


```{r}
rho<-0.5
U<-sqrt(rho)*y+sqrt(1-rho)*rnorm(dim)
head(t(U))
```



$$
X_{it}=1_{\hat U_{it}\le Y}\tag{3}
$$

$$
G(y)\equiv \mathrm{P}(X_t=1|y_t=y)=\Phi\left( \frac{Y-\sqrt{\rho_A}y}{\sqrt{1-\rho_A}} \right)\tag{4}\\
\therefore Y=\sqrt{1-\rho_A}G^{-1}(y)+\sqrt{\rho_A}y
$$


```{r}
Y<-sqrt(1-rho)*y+sqrt(rho)*y
```


```{r}
X<-rep(0,dim)
X[(U<=Y)]<-1 
X
mean(X)
mean(dnorm(y))
```

```{r}
dnorm(y)
```


```{r}
Y<-function() {
  rnorm()
}
  sqrt(1-rho)
  
  dnorm((Y-sqrt(rho)*y)/sqrt(1-rho),0,1)

```






```{r}
n<-1e4
rho<-0.6
mean<-c(0,0)
sigma<-matrix(c(1,rho,rho,1),ncol=2);sigma
x<-rmvnorm(n,mean = mean,sigma=sigma)
par(pty="s");plot(x)

```




```{r}
```


```{r}

```





```{r}
```


```{r}
```

